name: Version increment
on:
  push:
    branches:
      - develop
jobs:
  version_increment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Calculate new version code
        id: new-version-code
        run: |
          echo "Build number ${{ github.run_number }}"
      - name: Bump version
        uses: chkfung/android-version-actions@v1.1
        with:
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}
