name: Build
on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
  push:
    branches:
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
