name: Version increment
on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
jobs:
  version_increment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Increase version in branch $GITHUB_HEAD_REF ${{github.head_ref}}"
      - name: "Check Condition"
        if: ${{ GITHUB_HEAD_REF == 'test/**' }}
        run: echo "Meet the condition"
